### ISSUE TITLE
Can't create a pull request

### ISSUE THREAD

**Issue by CptIceberg** [odddollar/Language-benchmarks#4]
Hello,
I can't push my branch to this project, as the permission is denied. What can i do to contribute (i just made the php benchmarks) ?

**Comment by odddollar** [comment]
Hi
In order to push to a public repo, you have to fork it to your account.
Click the fork button, then clone this fork to your pc. Checkout a new branch then commit your additions to that branch and push back to the fork. Go to the github repo of the fork and click "create pull request", selecting the master branch of this repo and the new feature branch of your fork.

**Comment by CptIceberg** [comment]
Thank you, it's my first open-source contribution ;)
